---
title: "TP_Imputation_Multiple"
author: "Vincent LE MEUR"
date: "2024-02-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Imputation multiple

## Compte rendu

## Partie 1: TP
```{r, echo=FALSE,warning=FALSE, include=FALSE}

library(mice) # charge la librairie mice
library(VIM)


```

```{r, echo=FALSE,warning=FALSE, include=TRUE}
d = data.frame(airquality) #c'est une base de donnée pré-installée avec R
str(d) # affiche la structure (le type) des données

d$Month = as.factor(d$Month) # on les met en facteur
d$Day = as.factor(d$Day)

summary(d)


```

```{r, echo=FALSE,warning=FALSE, include=TRUE}

md.pattern(d)
cat("On remarque que les variables Ozone et Solar.R présentent des valauers manquantes")

marginplot(airquality[, c("Ozone","Wind")], col = mdc(c("obs", "mis")), cex = 1.2, cex.lab = 1.2,pch=19)

marginplot(airquality[, c("Ozone","Solar.R")], col = mdc(c("obs", "mis")), cex = 1.2, cex.lab = 1.2,pch=19)
```

boxplot assez proche -> mcar

Avec 7 individus on ne peut pas dire grand chose

```{r, echo=FALSE,warning=FALSE, include=TRUE}
d = d[,c(1:4)]
dm = mice(d, m = 5, seed=10, print = FALSE, maxit = 50)
summary(dm)

#pmm il prendd les x valeurs les pluys ⁾roches et prend l'une d('elle)



print(dm$imp)

d1 = complete(dm,1)
summary(d1)
d2 = complete(dm,2)
summary(d2)
d3 = complete(dm,3)
summary(d3)
d4 = complete(dm,4)
summary(d4)
d5 = complete(dm,5)
summary(d5)
```
```{r, echo=FALSE,warning=FALSE, include=TRUE}
library(lattice)
stripplot(dm, pch = 20, cex = 1.2)

xyplot(dm, Ozone ~ Solar.R|.imp, pch = 20, cex = 1.4)

par(mfrow=c(1,2))
hist(d[,1], col="lightblue", probability = TRUE, xlab = "Ozone", main = "Ozone")
hist(d1[,1], density = 2, add= TRUE, border = "red", probability = TRUE, col ="red")

hist(d[,2], col="lightblue", probability = TRUE, xlab = "Solar.R", main = "Solar.R")
hist(d1[,2], density = 2, add= TRUE, border = "red", probability = TRUE, col ="red")


```

```{r, echo=FALSE,warning=FALSE, include=TRUE}

fit <- with(dm, lm(Ozone ~ Solar.R + Wind + Temp))


#print(fit[1])
#print(fit[2])
#print(fit[3])
#print(fit[4])

sapply(fit$analyse, coef)
print(fit[4]$analyses[1])

fitpool = pool(fit)
summary(fitpool)

fitpool$qhat
fitpool$qba
```
## Partie 2: Rendu